spring:
  application:
    name: userCenter
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/universe
      username: root
      password: Nate12138
server:
  port: 8080
